
name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - retype

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest
        env:
          INPUT_OVERRIDE_BASE="{ \"url\": \"cbioportal.github.io/documentation\" }"
      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
        env:
          INPUT_OVERRIDE_BASE="{ \"url\": \"cbioportal.github.io/documentation\" }"